<a href="https://colab.research.google.com/github/golshidr/Augmentation-methods-datasets/blob/main/credit_card_frauds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **library**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import random
import numpy as np
from imblearn.datasets import fetch_datasets
from pandas.io.parsers.readers import read_csv
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import BernoulliNB

In [ ]:

df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')

In [ ]:
df.head(2)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  

[2 rows x 31 columns]

In [ ]:
df1=df[df['Class']==0]
df1.shape

(284315, 31)

In [ ]:
df1=df[df['Class']==1]
df1.shape

(492, 31)

# **naive bayes**

In [ ]:
def naive_approach(dfs):
    for i in range(1):
        index = 0
        df_1 = df.loc[df['Class'] == 1]
        df_0 = df.loc[df['Class'] == 0]
        n=(len(df_0)-len(df_1))
        new_data=pd.DataFrame()
        dfs_0=pd.DataFrame()
        print('Shape of dataframe in the first step:',df.shape)
        print('number of class 0:',df_0.shape)
        print('number of class 1:',df_1.shape)
        j=0
        while(index<=30):
            colname = df_1.columns[index]
            col = getattr(df_1, colname)
            max_value = col.max()
            min_value = col.min()
            random_float_list = []
            j=0
            # Generating data in each column
            for i in range(0, n):
              random_float_list.append(round(random.uniform(min_value, max_value), 5))
              
            np.reshape(random_float_list,(n,1))
            new_data[df_1.columns[index]]=random_float_list
            
            index+=1
            
    new_data[new_data.columns[-1]] == 1
    df_1=df_1.append(new_data)
    df_baseline=df_0.append(df_1)
    
    print('shape of new data that has been generated:',new_data.shape)
    print('Shape of class with label 1: ',df_1.shape)
    print('Shape of class with label 0: ',df_0.shape)
    print('Shape of dfs_0 at last: ',df_baseline.shape)
    df_baseline.to_csv('/content/drive/MyDrive/creditcard_baseline.csv')


naive_approach=naive_approach(df) 

Shape of dataframe in the first step: (284807, 31)
number of class 0: (284315, 31)
number of class 1: (492, 31)
shape of new data that has been generated: (283823, 31)
Shape of class with label 1:  (284315, 31)
Shape of class with label 0:  (284315, 31)
Shape of dfs_0 at last:  (568630, 31)


In [ ]:
def mean_approach(dfs):
    for i in range(1):
        index = 0
        df_1 = df.loc[df['Class'] == 1]
        df_0 = df.loc[df['Class'] == 0]
        n=(len(df_0)-len(df_1))
        new_data=pd.DataFrame()
        dfs_0=pd.DataFrame()
        print('Shape of dataframe in the first step:',df.shape)
        j=0
        while(index<=30):
            colname = df_1.columns[index]
            col = getattr(df_1, colname)
            mean_value = col.mean()
            max_value = col.max()
            std_value=col.std()
            min_value = col.min()
            mean_float_list = []
            j=0
            # Generating data in each column
            for i in range(0, n):
              z= mean_value - std_value
              mean_float_list.append(z)
              

            random.shuffle(mean_float_list)  
            np.reshape(mean_float_list,(n,1))
            new_data[df_1.columns[index]]=mean_float_list
            
            index+=1
            
    new_data[new_data.columns[-1]] == 1
    df_1=df_1.append(new_data)
    dfs_0=df_0.append(df_1)
    
    print('shape of new data that has been generated:',new_data.shape)
    print('Shape of class with label 1: ',df_1.shape)
    print('Shape of class with label 0: ',df_0.shape)
    print('Shape of df at last: ',dfs_0.shape)
    df_baseline.to_csv('/content/drive/MyDrive/creditcard_baseline_mean_std.csv')

mean_approach=mean_approach(df) 

Shape of dataframe in the first step: (284807, 31)
shape of new data that has been generated: (283823, 31)
Shape of class with label 1:  (284315, 31)
Shape of class with label 0:  (284315, 31)
Shape of dfs_0 at last:  (568630, 31)


# **classification**

In [ ]:
df1=df

In [ ]:
#df_baseline=read_csv('/content/drive/My Drive/creditcard_baseline_mean_std.csv')
#df_baseline=df_baseline.drop('Unnamed: 0',axis=1)

X=df.iloc[:,1:30].values
y=df.iloc[:,-1].values
acc=0
f1=0
i=0
class_0_org = df[df['Class'] == 0]
class_1_org = df[df['Class'] == 1]

class_0 = df[df.iloc[:,-1] == 0]
class_1 = df[df.iloc[:,-1] == 1]

print('knn:\n')
print('The shape of real data class 0:\n',class_0_org.shape)
print('The shape of real data class 1:\n',class_1_org.shape)
print('The shape of generated data class 0:\n',class_0.shape)
print('The shape of generated data class 1:\n',class_1.shape)

for j in range(0,len(class_1_org),50):
  class_1_test=class_1_org.iloc[j:j+50] # extract from orginal data
  class_1 = class_1.loc[:,~class_1.columns.duplicated()].reset_index(drop=True)
  class_1_train=pd.concat([class_1, class_1_test]).drop_duplicates(keep=False)
  class_1_train.drop(class_1_train.iloc[:, 30:], inplace = True, axis = 1)
  class_1_train["Class"] = 1
  i=i+1

  

  class_0_test=class_0_org.iloc[j:j+50] # extract from orginal data
  class_0 = class_0.loc[:,~class_0.columns.duplicated()].reset_index(drop=True)
  class_0_train=pd.concat([class_0, class_0_test]).drop_duplicates(keep=False)
  class_0_train.drop(class_0_train.iloc[:, 30:], inplace = True, axis = 1)
  class_0_train["Class"] = 0


  train_data = class_1_train.append(class_0_train)
  test_data = class_1_test.append(class_0_test)


  
  X_train=train_data.iloc[:,1:30].values
  X_train=pd.DataFrame(X_train)
  X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)



  Y_train=train_data.iloc[:,-1].values
  Y_train=pd.DataFrame(Y_train)
  Y_train = Y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)




  X_test=test_data.iloc[:,1:30].values
  
  X_test=pd.DataFrame(X_test)
  
  Y_test=test_data.iloc[:,-1].values
  Y_test=pd.DataFrame(Y_test)


  model = KNeighborsClassifier(n_neighbors=5)
  #model=RandomForestClassifier(n_estimators=1000)
  #model=SVC(kernel='rbf')
  #model = BernoulliNB()
  #model = GaussianNB()
  #model=MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(35,20), random_state=1,max_iter=1500)
  #model=SGDClassifier(loss="hinge", penalty="l2", max_iter=50)


  model.fit(X_train,Y_train.values.ravel())
  Y_pred_train=model.predict(X_train)
  Y_pred_test=model.predict(X_test)



  #print('Test: consfusion matrix :\n',confusion_matrix(Y_test,Y_pred_test))
  f1=f1+f1_score(Y_test,Y_pred_test)
  acc=acc+accuracy_score(Y_test,Y_pred_test)

print(f1/i)
print(acc/i)

knn:

The shape of real data class 0:
 (284315, 31)
The shape of real data class 1:
 (492, 31)
The shape of generated data class 0:
 (284315, 31)
The shape of generated data class 1:
 (492, 31)


# **SMOTE**

In [ ]:
#SMOTE

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix
df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')

class_0_org = df[df['Class'] == 0]
class_1_org = df[df['Class'] == 1]

print('the shape of data befor oversampling:',df.shape)

X=df.iloc[:,0:30].values
Y=df.iloc[:,-1].values

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X, Y = sm.fit_resample(X, Y.ravel())

X=pd.DataFrame(X)
Y=pd.DataFrame(Y)
df = pd.concat([X, Y], axis=1)
print('the shape of data after oversampling:',df.shape)
df.to_csv('/content/drive/My Drive/SMOTE_creditcard.csv')
class_0 = df[df.iloc[:,-1] == 0]
class_1 = df[df.iloc[:,-1] == 1]




for j in range(0,len(class_1_org),50):
  class_1_test=class_1_org.iloc[j:j+50] # extract from orginal data
  class_1 = class_1.loc[:,~class_1.columns.duplicated()].reset_index(drop=True)
  class_1_train=pd.concat([class_1, class_1_test]).drop_duplicates(keep=False)
  class_1_train.drop(class_1_train.iloc[:, 31:], inplace = True, axis = 1)
  class_1_train["Class"] = 1

  

  class_0_test=class_0_org.iloc[j:j+50] # extract from orginal data
  class_0 = class_0.loc[:,~class_0.columns.duplicated()].reset_index(drop=True)
  class_0_train=pd.concat([class_0, class_0_test]).drop_duplicates(keep=False)
  class_0_train.drop(class_0_train.iloc[:, 31:], inplace = True, axis = 1)
  class_0_train["Class"] = 0


  train_data = class_1_train.append(class_0_train)
  test_data = class_1_test.append(class_0_test)


  
  X_train=train_data.iloc[:,0:30].values
  X_train=pd.DataFrame(X_train)
  X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)



  Y_train=train_data.iloc[:,-1].values
  Y_train=pd.DataFrame(Y_train)
  Y_train = Y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)




  X_test=test_data.iloc[:,0:30].values
  
  X_test=pd.DataFrame(X_test)
  
  Y_test=test_data.iloc[:,-1].values
  Y_test=pd.DataFrame(Y_test)


  #model = KNeighborsClassifier(n_neighbors=5)
  #model=RandomForestClassifier(n_estimators=1000)
  #model=SVC(kernel='rbf')
  #model = BernoulliNB()
  #model = GaussianNB()
  model=MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(45,20), random_state=1,max_iter=300)
  #model=SGDClassifier(loss="hinge", penalty="l2", max_iter=50)
  model.fit(X_train,Y_train.values.ravel())
  Y_pred_train=model.predict(X_train)
  Y_pred_test=model.predict(X_test)



  print('Test: consfusion matrix :\n',confusion_matrix(Y_test,Y_pred_test))



the shape of data befor oversampling: (284807, 31)
the shape of data after oversampling: (568630, 31)
Test: consfusion matrix :
 [[50  0]
 [ 1 49]]
Test: consfusion matrix :
 [[50  0]
 [ 2 48]]
Test: consfusion matrix :
 [[50  0]
 [ 1 49]]
Test: consfusion matrix :
 [[50  0]
 [10 40]]
Test: consfusion matrix :
 [[50  0]
 [10 40]]
Test: consfusion matrix :
 [[50  0]
 [ 2 48]]
Test: consfusion matrix :
 [[50  0]
 [ 2 48]]
Test: consfusion matrix :
 [[50  0]
 [ 9 41]]
Test: consfusion matrix :
 [[50  0]
 [ 4 46]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:699: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Test: consfusion matrix :
 [[34 16]
 [ 4 38]]


# **K-means SMOTE**

In [ ]:
import pandas as pd
import numpy as np
import random
import numpy as np
from imblearn.datasets import fetch_datasets
from pandas.io.parsers.readers import read_csv
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,precision_score,recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn import preprocessing
from sklearn.gaussian_process import GaussianProcessClassifier

In [ ]:
def metrics_computation(real_values,pred_values):
   CM = confusion_matrix(real_values,pred_values)
   TN = CM[0][0] 
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   precision_min = round( TP / (TP+FP),4 )
   recall_min = round( TP / (TP+FN),4 )
   f1_min = 2/((1/precision_min)+(1/recall_min))
   return (precision_min,recall_min,f1_min)

In [ ]:
  model_pipeline=[]
  model_pipeline.append(GaussianNB())
  model_pipeline.append(SGDClassifier(loss='hinge',penalty="l2", max_iter=1500))
  model_pipeline.append(KNeighborsClassifier(n_neighbors=3))
  model_pipeline.append(MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(30,35), random_state=1,max_iter=1500))
  model_pipeline.append(RandomForestClassifier(n_estimators=15))
  model_pipeline.append(SVC(kernel='sigmoid'))

In [ ]:
"""K-Means SMOTE oversampling method for class-imbalanced data"""

# Authors: Felix Last
# License: MIT

import warnings
import math
import copy
import numpy as np

from sklearn.utils import check_random_state
from sklearn.metrics.pairwise import euclidean_distances

from imblearn.over_sampling.base import BaseOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler
from imblearn.exceptions import raise_isinstance_error
from imblearn.utils import check_neighbors_object
from imblearn.utils.deprecation import deprecate_parameter

class KMeansSMOTE(BaseOverSampler):
    """Class to perform oversampling using K-Means SMOTE.

    K-Means SMOTE works in three steps:

    1. Cluster the entire input space using k-means.
    2. Distribute the number of samples to generate across clusters:

        1. Select clusters which have a high number of minority class samples.
        2. Assign more synthetic samples to clusters where minority class samples are sparsely distributed.

    3. Oversample each filtered cluster using SMOTE.

    The method implements SMOTE and random oversampling as limit cases. Therefore, the following configurations
    may be used to achieve the behavior of ...

    ... SMOTE: ``imbalance_ratio_threshold=float('Inf'), kmeans_args={'n_clusters':1}``

    ... random oversampling: ``imbalance_ratio_threshold=float('Inf'), kmeans_args={'n_clusters':1}, smote_args={'k_neighbors':0})``

    Parameters
    ----------
    sampling_strategy : str, dict, or callable, optional (default='auto')
        Ratio to use for resampling the data set.

        - If ``str``, has to be one of: (i) ``'minority'``: resample the
          minority class; (ii) ``'majority'``: resample the majority class,
          (iii) ``'not minority'``: resample all classes apart of the minority
          class, (iv) ``'all'``: resample all classes, and (v) ``'auto'``:
          correspond to ``'all'`` with for oversampling methods and ``'not
          minority'`` for undersampling methods. The classes targeted will be
          oversampled or undersampled to achieve an equal number of sample
          with the majority or minority class.
        - If ``dict``, the keys correspond to the targeted classes. The values
          correspond to the desired number of samples.
        - If callable, function taking ``y`` and returns a ``dict``. The keys
          correspond to the targeted classes. The values correspond to the
          desired number of samples.

    random_state : int, RandomState instance or None, optional (default=None)
        If int, ``random_state`` is the seed used by the random number
        generator; If ``RandomState`` instance, random_state is the random
        number generator; If ``None``, the random number generator is the
        ``RandomState`` instance used by ``np.random``.
        Will be copied to kmeans_args and smote_args if not explicitly passed there.

    kmeans_args : dict, optional (default={})
        Parameters to be passed to ``sklearn.cluster.KMeans`` or ``sklearn.cluster.MiniBatchKMeans``
        (see ``use_minibatch_kmeans``). If n_clusters is not explicitly set, scikit-learn's
        default will apply.

    smote_args : dict, optional (default={})
        Parameters to be passed to ``imblearn.over_sampling.SMOTE``. Note that ``k_neighbors`` is automatically
        adapted without warning when a cluster is smaller than the number of neighbors specified.
        `sampling_strategy` will be overwritten according to sampling_strategy passed to this class. `random_state`
        will be passed from this class if none is specified.

    imbalance_ratio_threshold : float or dict, optional (default=1.0)
        Specify a threshold for a cluster's imbalance ratio  ``((majority_count + 1) / (minority_count + 1))``.
        Only clusters with an imbalance ratio less than the threshold are oversampled. Use a dictionary to specify
        different thresholds for different minority classes.

    density_power : float, optional (default=None)
        Used to compute the density of minority samples within each cluster. By default, the number of features will be used.

    use_minibatch_kmeans : boolean, optional (default=True)
        If False, use ``sklearn.cluster.KMeans``. If True, use ``sklearn.cluster.MiniBatchKMeans``.

    n_jobs : int, optional (default=1)
        The number of threads to open if possible. This parameter will be copied to ``kmeans_args`` and
        ``smote_args`` if not explicitly passed there. Note: ``MiniBatchKMeans`` does not accept ``n_jobs``.

    Examples
    --------


    """

    def __init__(self,
                sampling_strategy='auto',
                random_state=None,
                kmeans_args=None,
                smote_args=None,
                imbalance_ratio_threshold=1.0,
                density_power=None,
                use_minibatch_kmeans=True,
                n_jobs=1,
                **kwargs):
        super(KMeansSMOTE, self).__init__(sampling_strategy=sampling_strategy, **kwargs)
        if kmeans_args is None:
            kmeans_args = {}
        if smote_args is None:
            smote_args = {}
        self.imbalance_ratio_threshold = imbalance_ratio_threshold
        self.kmeans_args = copy.deepcopy(kmeans_args)
        self.smote_args = copy.deepcopy(smote_args)
        self.random_state = random_state
        self.n_jobs = n_jobs
        self.use_minibatch_kmeans = use_minibatch_kmeans

        self.density_power = density_power

    def _cluster(self, X):
        """Run k-means to cluster the dataset

        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
            Matrix containing the data which have to be sampled.

        Returns
        -------
        cluster_assignment : ndarray, shape (n_samples)
            The corresponding cluster labels of ``X``.
        """

        if self.use_minibatch_kmeans:
            from sklearn.cluster import MiniBatchKMeans as KMeans
        else:
            from sklearn.cluster import KMeans as KMeans

        kmeans = KMeans(**self.kmeans_args)
        if self.use_minibatch_kmeans and 'init_size' not in self.kmeans_args:
            self.kmeans_args['init_size'] = min(2 * kmeans.n_clusters, X.shape[0])
            kmeans = KMeans(**self.kmeans_args)

        kmeans.fit_transform(X)
        cluster_assignment = kmeans.labels_
        # kmeans.labels_ does not use continuous labels,
        # i.e. some labels in 0..n_clusters may not exist. Tidy up this mess.
        return cluster_assignment

    def _filter_clusters(self, X, y, cluster_assignment, minority_class_label):
        """Determine sampling weight for each cluster.

        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
            Matrix containing the data which have to be sampled.
        y : ndarray, shape (n_samples, )
            Corresponding label for each sample in X.
        cluster_assignment : ndarray, shape (n_samples)
            The corresponding cluster labels of ``X``.
        minority_class_label : int
            Label of the minority class to filter by.

        Returns
        -------
        sampling_weights : ndarray, shape (np.max(np.unique(cluster_assignment)),)
            Vector of sampling weights for each cluster
        """
        # compute the shape of the density factors
        # since the cluster labels are not continuous, make it large enough
        # to fit all values up to the largest cluster label
        largest_cluster_label = np.max(np.unique(cluster_assignment))
        sparsity_factors = np.zeros((largest_cluster_label + 1,), dtype=np.float64)
        minority_mask = (y == minority_class_label)
        sparsity_sum = 0
        imbalance_ratio_threshold = self.imbalance_ratio_threshold
        if isinstance(imbalance_ratio_threshold, dict):
            imbalance_ratio_threshold = imbalance_ratio_threshold[minority_class_label]

        for i in np.unique(cluster_assignment):
            cluster = X[cluster_assignment == i]
            mask = minority_mask[cluster_assignment == i]
            minority_count = cluster[mask].shape[0]
            majority_count = cluster[~mask].shape[0]
            imbalance_ratio = (majority_count + 1) / (minority_count + 1)
            if (imbalance_ratio < imbalance_ratio_threshold) and (minority_count > 1):
                distances = euclidean_distances(cluster[mask])
                non_diagonal_distances = distances[
                    ~np.eye(distances.shape[0], dtype=np.bool)
                ]
                average_minority_distance = np.mean( non_diagonal_distances )
                if average_minority_distance is 0: average_minority_distance = 1e-1 # to avoid division by 0
                density_factor = minority_count / (average_minority_distance ** self.density_power)
                sparsity_factors[i] = 1 / density_factor

        # prevent division by zero; set zero weights in majority clusters
        sparsity_sum = sparsity_factors.sum()
        if sparsity_sum == 0:
            sparsity_sum = 1 # to avoid division by zero
        sparsity_sum = np.full(sparsity_factors.shape, sparsity_sum, np.asarray(sparsity_sum).dtype)
        sampling_weights = (sparsity_factors / sparsity_sum)

        return sampling_weights


    def _fit_resample(self, X, y):
        """Resample the dataset.

        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
            Matrix containing the data which have to be sampled.

        y : ndarray, shape (n_samples, )
            Corresponding label for each sample in X.

        Returns
        -------
        X_resampled : ndarray, shape (n_samples_new, n_features)
            The array containing the resampled data.

        y_resampled : ndarray, shape (n_samples_new)
            The corresponding labels of ``X_resampled``

        """
        self._set_subalgorithm_params()

        if self.density_power is None:
            self.density_power = X.shape[1]

        resampled = [ (X.copy(), y.copy()) ]
        sampling_ratio = {k: v for k, v in self.sampling_strategy_.items()}
        # sampling_strategy_ does not contain classes where n_samples 0
        for class_label in np.unique(y):
            if class_label not in sampling_ratio:
                sampling_ratio[class_label] = 0
        for minority_class_label, n_samples in sampling_ratio.items():
            if n_samples == 0:
                continue

            cluster_assignment = self._cluster(X)
            sampling_weights = self._filter_clusters(X, y, cluster_assignment, minority_class_label)
            smote_args = self.smote_args.copy()
            if np.count_nonzero(sampling_weights) > 0:
                # perform k-means smote
                for i in np.unique(cluster_assignment):
                    cluster_X = X[cluster_assignment == i]
                    cluster_y = y[cluster_assignment == i]
                    if sampling_weights[i] > 0:
                        # determine ratio for oversampling the current cluster
                        target_ratio = {label: np.count_nonzero(cluster_y == label) for label in sampling_ratio}
                        cluster_minority_count = np.count_nonzero(cluster_y == minority_class_label)
                        generate_count = int(round(n_samples * sampling_weights[i]))
                        target_ratio[minority_class_label] = generate_count + cluster_minority_count

                        # make sure that cluster_y has more than 1 class, adding a random point otherwise
                        remove_index = -1
                        if np.unique(cluster_y).size < 2:
                            remove_index = cluster_y.size
                            cluster_X = np.append(cluster_X, np.zeros((1,cluster_X.shape[1])), axis=0)
                            majority_class_label = next( key for key in sampling_ratio.keys() if key != minority_class_label )
                            target_ratio[majority_class_label] = 1 + target_ratio[majority_class_label]
                            cluster_y = np.append(cluster_y, np.asarray(majority_class_label).reshape((1,)), axis=0)

                        # clear target ratio of labels not present in cluster
                        for label in list(target_ratio.keys()):
                            if label not in cluster_y:
                                del target_ratio[label]

                        # modify copy of the user defined smote_args to reflect computed parameters
                        smote_args['sampling_strategy'] = target_ratio

                        smote_args = self._validate_smote_args(smote_args, cluster_minority_count)
                        oversampler = SMOTE(**smote_args)

                        # if k_neighbors is 0, perform random oversampling instead of smote
                        if 'k_neighbors' in smote_args and smote_args['k_neighbors'] == 0:
                                oversampler_args = {}
                                if 'random_state' in smote_args:
                                    oversampler_args['random_state'] = smote_args['random_state']
                                oversampler = RandomOverSampler(**oversampler_args)

                        # finally, apply smote to cluster
                        with warnings.catch_warnings():
                            # ignore warnings about minority class getting bigger than majority class
                            # since this would only be true within this cluster
                            warnings.filterwarnings(action='ignore', category=UserWarning, message=r'After over-sampling, the number of samples \(.*\) in class .* will be larger than the number of samples in the majority class \(class #.* \-\> .*\)')
                            cluster_resampled_X, cluster_resampled_y = oversampler.fit_resample(cluster_X, cluster_y)

                        if remove_index > -1:
                            # since SMOTE's results are ordered the same way as the data passed into it,
                            # the temporarily added point is at the same index position as it was added.
                            for l in [cluster_resampled_X, cluster_resampled_y, cluster_X, cluster_y]:
                                np.delete(l, remove_index, 0)

                        # add new generated samples to resampled
                        resampled.append( (
                            cluster_resampled_X[cluster_y.size:,:],
                            cluster_resampled_y[cluster_y.size:]))
            else:
                # all weights are zero -> perform regular smote
                warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
                target_ratio = {label: np.count_nonzero(y == label) for label in sampling_ratio}
                target_ratio[minority_class_label] = sampling_ratio[minority_class_label]
                minority_count = np.count_nonzero(y == minority_class_label)
                smote_args = self._validate_smote_args(smote_args, minority_count)
                oversampler = SMOTE(**smote_args)
                X_smote, y_smote = oversampler.fit_resample(X, y)
                resampled.append((
                    X_smote[y.size:,:],
                    y_smote[y.size:]))


        resampled = list(zip(*resampled))
        if(len(resampled) > 0):
            X_resampled = np.concatenate(resampled[0], axis=0)
            y_resampled = np.concatenate(resampled[1], axis=0)
        return X_resampled, y_resampled


    def _validate_smote_args(self, smote_args, minority_count):
        # determine max number of nearest neighbors considering sample size
        max_k_neighbors =  minority_count - 1
        # check if max_k_neighbors is violated also considering smote's default
        smote = SMOTE(**smote_args)
        if smote.k_neighbors > max_k_neighbors:
            smote_args['k_neighbors'] = max_k_neighbors
            smote = SMOTE(**smote_args)
        return smote_args

    def _set_subalgorithm_params(self):
        # copy random_state to sub-algorithms
        if self.random_state is not None:
            if 'random_state' not in self.smote_args:
                    self.smote_args['random_state'] = self.random_state
            if 'random_state' not in self.kmeans_args:
                self.kmeans_args['random_state'] = self.random_state

        # copy n_jobs to sub-algorithms
        if self.n_jobs is not None:
            if 'n_jobs' not in self.smote_args:
                    self.smote_args['n_jobs'] = self.n_jobs
            if 'n_jobs' not in self.kmeans_args:
                if not self.use_minibatch_kmeans:
                    self.kmeans_args['n_jobs'] = self.n_jobs

In [ ]:
# SMOTE clusterd
import warnings
warnings.filterwarnings("ignore")



class_0_org = df[df['Class'] == 0]
class_1_org = df[df['Class'] == 1]

X=df.iloc[:,0:29].values
y=df.iloc[:,-1].values

[print('Class {} has {} instances'.format(label, count))
 for label, count in zip(*np.unique(y, return_counts=True))]

kmeans_smote = KMeansSMOTE(
    kmeans_args={
        'n_clusters': 20
    },
    smote_args={
        'k_neighbors': 10
    }
)
X_resampled, y_resampled = kmeans_smote.fit_resample(X, y)

[print('Class {} has {} instances after oversampling'.format(label, count))
 for label, count in zip(*np.unique(y_resampled, return_counts=True))]


X=pd.DataFrame(X_resampled)
Y=pd.DataFrame(y_resampled)
df_clusterd = pd.concat([X, Y], axis=1)


class_0 = df_clusterd[df_clusterd.iloc[:,-1] == 0]
class_1 = df_clusterd[df_clusterd.iloc[:,-1] == 1]

model_list=['naive bayes','SGD','KNN','MLP','random forest','svm']

acc_list_final=[]
pr_minority_list_final=[]
recall_minority_list_final=[]
f1_minority_list_final=[]

f1_list_final_micro=[]
f1_list_final_macro=[]
f1_list_final_weighted=[]

pr_list_final_micro=[]
pr_list_final_macro=[]
pr_list_final_weighted=[]

recall_list_final_micro=[]
recall_list_final_macro=[]
recall_list_final_weighted=[]



for model in model_pipeline:
  f1_minority_list=[]
  f1_list_micro=[]
  f1_list_macro=[]
  f1_list_weighted=[]
  acc_list=[]
  pr_list_micro=[]
  pr_list_macro=[]
  pr_list_weighted=[]
  recall_list_micro=[]
  recall_list_macro=[]
  recall_list_weighted=[]
  pr_minority_list=[]
  recall_minority_list=[]

  for j in range(0,len(class_1_org),150):
    class_1_test=class_1_org.iloc[j:j+150] # extract from orginal data
    class_1 = class_1.loc[:,~class_1.columns.duplicated()].reset_index(drop=True)
    class_1_train=pd.concat([class_1, class_1_test]).drop_duplicates(keep=False)
    class_1_train.drop(class_1_train.iloc[:, 29:], inplace = True, axis = 1)
    class_1_train["Class"] = 1

    

    class_0_test=class_0_org.iloc[j:j+150] # extract from orginal data
    class_0 = class_0.loc[:,~class_0.columns.duplicated()].reset_index(drop=True)
    class_0_train=pd.concat([class_0, class_0_test]).drop_duplicates(keep=False)
    class_0_train.drop(class_0_train.iloc[:, 29:], inplace = True, axis = 1)
    class_0_train["Class"] = 0


    train_data = class_1_train.append(class_0_train)
    test_data = class_1_test.append(class_0_test)


    
    X_train=train_data.iloc[:,0:29].values
    X_train=pd.DataFrame(X_train)
    X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)



    Y_train=train_data.iloc[:,-1].values
    Y_train=pd.DataFrame(Y_train)
    Y_train = Y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

    X_test=test_data.iloc[:,0:29].values
    
    X_test=pd.DataFrame(X_test)
    
    Y_test=test_data.iloc[:,-1].values
    Y_test=pd.DataFrame(Y_test)



    model.fit(X_train,Y_train.values.ravel())
    Y_pred_test=model.predict(X_test)

    acc=accuracy_score(Y_test,Y_pred_test)
    acc_list.append(round((acc),4))
    
    pr_minority, recall_minority,f1_minority =metrics_computation(Y_test,Y_pred_test)

    pr_minority_list.append(round((pr_minority),4))
    recall_minority_list.append(round((recall_minority),4))
    f1_minority_list.append(round((f1_minority),4))
    
    f1=f1_score(Y_test,Y_pred_test,average='weighted')
    f1_list_weighted.append(round((f1),4))
    f1=f1_score(Y_test,Y_pred_test,average='micro')
    f1_list_micro.append(round((f1),4))
    f1=f1_score(Y_test,Y_pred_test,average='macro')
    f1_list_macro.append(round((f1),4))

    pr=precision_score(Y_test,Y_pred_test,average='weighted')
    pr_list_weighted.append(round((pr),4))
    pr=precision_score(Y_test,Y_pred_test,average='micro')
    pr_list_micro.append(round((pr),4))
    pr=precision_score(Y_test,Y_pred_test,average='macro')
    pr_list_macro.append(round((pr),4))

    recall=recall_score(Y_test,Y_pred_test,average='weighted')
    recall_list_weighted.append(round((recall),4))
    recall=recall_score(Y_test,Y_pred_test,average='micro')
    recall_list_micro.append(round((recall),4))
    recall=recall_score(Y_test,Y_pred_test,average='macro')
    recall_list_macro.append(round((recall),4))


  
  acc_list_final.append(round(np.mean(acc_list),4))
  pr_minority_list_final.append(round(np.mean(pr_minority_list),4))
  recall_minority_list_final.append(round(np.mean(recall_minority_list),4))
  f1_minority_list_final.append(round(np.mean(f1_minority_list),4))

  f1_list_final_micro.append(round(np.mean(f1_list_micro),4))
  f1_list_final_macro.append(round(np.mean(f1_list_macro),4))
  f1_list_final_weighted.append(round(np.mean(f1_list_weighted),4))

  pr_list_final_micro.append(round(np.mean(pr_list_micro),4))
  pr_list_final_macro.append(round(np.mean(pr_list_macro),4))
  pr_list_final_weighted.append(round(np.mean(pr_list_weighted),4))

  recall_list_final_micro.append(round(np.mean(recall_list_micro),4))
  recall_list_final_macro.append(round(np.mean(recall_list_macro),4))
  recall_list_final_weighted.append(round(np.mean(recall_list_weighted),4))




Class 0 has 284315 instances
Class 1 has 492 instances
Class 0 has 284315 instances after oversampling
Class 1 has 284315 instances after oversampling


In [ ]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0],
           dtype='int64')

In [ ]:
#without augmentation


df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix
class_0_org = df[df['Class'] == 0]

class_1_org = df[df['Class'] == 1]

print('the shape of data befor oversampling:',df.shape)

X=df.iloc[:,0:30].values
Y=df.iloc[:,-1].values

X=pd.DataFrame(X)
Y=pd.DataFrame(Y)
df = pd.concat([X, Y], axis=1)
print('the shape of data after oversampling:',df.shape)
class_0 = df[df.iloc[:,-1] == 0]
class_1 = df[df.iloc[:,-1] == 1]




for j in range(0,len(class_1_org),50):
  class_1_test=class_1_org.iloc[j:j+50] # extract from orginal data
  class_1 = class_1.loc[:,~class_1.columns.duplicated()].reset_index(drop=True)
  class_1_train=pd.concat([class_1, class_1_test]).drop_duplicates(keep=False)
  class_1_train.drop(class_1_train.iloc[:, 30:], inplace = True, axis = 1)
  class_1_train["Class"] = 1

  

  class_0_test=class_0_org.iloc[j:j+50] # extract from orginal data
  class_0 = class_0.loc[:,~class_0.columns.duplicated()].reset_index(drop=True)
  class_0_train=pd.concat([class_0, class_0_test]).drop_duplicates(keep=False)
  class_0_train.drop(class_0_train.iloc[:, 30:], inplace = True, axis = 1)
  class_0_train["Class"] = 0


  train_data = class_1_train.append(class_0_train)
  test_data = class_1_test.append(class_0_test)


  
  X_train=train_data.iloc[:,0:30].values
  X_train=pd.DataFrame(X_train)
  X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)



  Y_train=train_data.iloc[:,-1].values
  Y_train=pd.DataFrame(Y_train)
  Y_train = Y_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)




  X_test=test_data.iloc[:,0:30].values
  
  X_test=pd.DataFrame(X_test)
  
  Y_test=test_data.iloc[:,-1].values
  Y_test=pd.DataFrame(Y_test)


  model = KNeighborsClassifier(n_neighbors=5)
  #model=RandomForestClassifier(n_estimators=100)
  #model=SVC(kernel='linear')
  #model = BernoulliNB()
  #model = GaussianNB()
  #model=MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(45,20), random_state=1,max_iter=300)
  #model=SGDClassifier(loss="hinge", penalty="l2", max_iter=50)
  model.fit(X_train,Y_train.values.ravel())
  Y_pred_train=model.predict(X_train)
  Y_pred_test=model.predict(X_test)



  print('Test: consfusion matrix :\n',confusion_matrix(Y_test,Y_pred_test))



the shape of data befor oversampling: (284807, 31)
the shape of data after oversampling: (284807, 31)
Test: consfusion matrix :
 [[48  2]
 [47  3]]
Test: consfusion matrix :
 [[50  0]
 [37 13]]
Test: consfusion matrix :
 [[50  0]
 [39 11]]
Test: consfusion matrix :
 [[50  0]
 [49  1]]
